import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Reliastra',
  description: 'Reliastra Terms of Service. Last updated August 2025.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <article className="py-24">
        <div className="max-w-3xl mx-auto px-4 md:px-8">
          <h1 className="text-3xl md:text-4xl font-bold text-[#09090B] tracking-tight">Terms of Service</h1>
          <p className="mt-2 text-sm text-[#A1A1AA]">Last updated: August 2025</p>
          <div className="mt-10 space-y-8 text-sm text-[#52525B] leading-relaxed">
            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using Reliastra (&ldquo;Service&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to all of these Terms, do not use the Service. These Terms apply to all visitors, users, and others who access or use the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">2. Description of Service</h2>
              <p>Reliastra provides an external dependency monitoring and intelligence platform. The Service monitors third-party APIs and services, provides incident correlation, generates SLA evidence reports, and delivers alerts. The Service is provided &ldquo;as is&rdquo; and &ldquo;as available.&rdquo;</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">3. User Accounts</h2>
              <p>You must register for an account to use certain features of the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">4. Acceptable Use</h2>
              <p>You agree not to use the Service to: (a) monitor APIs or services you do not have the right to monitor; (b) attempt to disrupt, overload, or interfere with the proper functioning of the Service; (c) use the Service for any unlawful purpose; (d) resell or redistribute the Service without written consent; (e) reverse engineer, decompile, or disassemble any part of the Service.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">5. Intellectual Property</h2>
              <p>The Service and its original content, features, and functionality are owned by Reliastra and are protected by international copyright, trademark, and other intellectual property laws. Our trademarks and trade dress may not be used in connection with any product or service without prior written consent.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">6. User Content</h2>
              <p>You retain ownership of any data you submit to the Service. By using the Service, you grant us a limited, non-exclusive license to process and store your data solely for the purpose of providing the Service. We do not share your monitoring data with third parties except as described in our Privacy Policy.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">7. Payment Terms</h2>
              <p>Paid plans are billed monthly in advance. Prices are subject to change with 30 days&apos; notice. All fees are non-refundable except as expressly stated in these Terms or required by applicable law. We reserve the right to suspend or terminate your account for non-payment.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">8. Service Level Agreement</h2>
              <p>We aim for high availability of the Service itself. Reliastra does not currently publish a formal uptime SLA or automatic service-credit schedule. SLA evidence reports generated by Reliastra relate to third-party vendors and do not constitute a guarantee of Reliastra&apos;s own uptime.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">9. Limitation of Liability</h2>
              <p>In no event shall Reliastra be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising out of or in connection with the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">10. Disclaimer of Warranties</h2>
              <p>The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, timely, secure, or error-free. Monitoring data is collected on a best-effort basis and may not reflect real-time conditions.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">11. Indemnification</h2>
              <p>You agree to indemnify and hold harmless Reliastra, its affiliates, and their respective officers, directors, employees, and agents from any claims, damages, losses, or expenses arising from your use of the Service or violation of these Terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">12. Termination</h2>
              <p>You may terminate your account at any time. We may suspend or terminate your account for violation of these Terms or for any other reason at our discretion. Upon termination, your right to use the Service ceases immediately. Sections 5, 6, 9, 10, and 11 survive termination.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">13. Modifications</h2>
              <p>We reserve the right to modify these Terms at any time. We will provide notice of material changes via email or a prominent notice on the Service. Your continued use after modifications constitutes acceptance of the updated Terms.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">14. Governing Law</h2>
              <p>These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Delaware.</p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-[#09090B] mb-3">15. Contact</h2>
              <p>For questions about these Terms, please contact us at <a href="mailto:legal@reliastra.com" className="text-[#0891B2] hover:underline">legal@reliastra.com</a>.</p>
            </section>
          </div>
        </div>
      </article>
    </main>
  );
}
